name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.
